image: node:12

before_script:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.0/hugo_extended_0.55.0_Linux-64bit.tar.gz | tar xz -C /bin/
  - yarn

test:
  stage: test
  script:
    - yarn check
    - hugo --minify
