baseURL = "https://www.spotlightpa.org/"
languageCode = "en-us"
title = "Spotlight PA"
description = "The mission of Spotlight PA is to hold powerful private and public forces across Pennsylvania — especially government, business and special interests — to account through urgent and compelling investigative journalism that leads to change and the betterment of democracy, the state and all who live here."
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

googleAnalytics = "UA-141126362-1"
[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
