[build]
base = ""
command = "hugo version && hugo --debug || { sleep 120; false; }"
publish = "public"

[build.environment]
HUGO_VERSION = "0.55.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
