[build]
base = ""
command = "yarn build:prod"
publish = "public"

[build.environment]
IMGPROXY_URL = "/imgproxy"
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"
NODE_VERSION = "12"

[context.deploy-preview]
command = "yarn build:stage"

[context.deploy-preview.processing]
skip_processing = true

[context.branch-deploy]
command = "yarn build:stage"

[context.branch-deploy.processing]
skip_processing = true

[[headers]]
for = "/*.(css|ttf|ttc|otf|eot|woff|woff2)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" # 1 year

[[headers]]
for = "/*.(jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)"
[headers.values]
Cache-Control = "public, max-age=1209600" # 2 weeks

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=300" # 5 minutes

[[headers]]
for = "/@src/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" # 1 year


[[headers]]
for = "/*.(woff|woff2)"
[headers.values]
Access-Control-Allow-Origin = "*"
